# Generated by Django 4.2.3 on 2024-07-15 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriumfeature',
            name='auditorium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='auditorium.auditorium'),
        ),
    ]
