# Generated by Django 4.2.3 on 2024-07-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditorium',
            old_name='use_use',
            new_name='username',
        ),
    ]
