# Generated by Django 4.2.3 on 2024-07-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0002_rename_user_auditorium_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditorium',
            old_name='username',
            new_name='user',
        ),
    ]
