# Generated by Django 4.2.3 on 2024-07-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0002_alter_auditoriumfeature_auditorium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriumfeature',
            name='feature',
            field=models.CharField(max_length=100),
        ),
    ]
