# Generated by Django 4.2.3 on 2024-07-16 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0003_alter_auditoriumfeature_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='cost',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='auditorium',
            name='ac_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditorium',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='auditoriums', to='auditorium.feature'),
        ),
        migrations.AddField(
            model_name='feature',
            name='auditorium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auditorium_features', to='auditorium.auditorium'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='capacity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='images',
            field=models.ImageField(blank=True, default='../static/images/blue_mac2.jpg', upload_to='auditorium_images/'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='location',
            field=models.CharField(default='Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AuditoriumFeature',
        ),
    ]
