# Generated by Django 4.2.3 on 2024-07-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0003_userrequest_delete_bookingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
