# Generated by Django 4.2.3 on 2024-07-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0004_userrequest_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='payment_requested',
            field=models.BooleanField(default=False),
        ),
    ]
