# Generated by Django 4.2.3 on 2024-07-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0004_rename_cost_feature_amount_auditorium_ac_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditorium',
            name='ac_status',
        ),
    ]
