# Generated by Django 4.2.3 on 2024-07-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0005_userrequest_payment_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
