# Generated by Django 4.2.3 on 2024-07-16 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0005_remove_auditorium_ac_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auditorium_images/')),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorium_images', to='auditorium.auditorium')),
            ],
        ),
    ]
