# Generated by Django 4.2.3 on 2024-07-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0006_userrequest_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
