# Generated by Django 4.2.3 on 2024-07-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0008_auditorium'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='auditorium_images/'),
        ),
    ]
