# Generated by Django 4.2.3 on 2024-07-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0009_bookingdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingDetail',
        ),
    ]
